from __future__ import annotations
from datetime import datetime
from enum import StrEnum
from sqlalchemy import BigInteger, Boolean, DateTime, Float, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
class Base(DeclarativeBase): pass
class RegistrationStatus(StrEnum): DRAFT="draft"; PENDING="pending"; PROVISIONING="provisioning"; ACTIVE="active"; FAILED="failed"; REJECTED="rejected"
class RegistrationStep(StrEnum): BRAND="brand"; BOT_TOKEN="bot_token"; BOT_ID="bot_id"; PANEL_URL="panel_url"; PANEL_USERNAME="panel_username"; PANEL_API_KEY="panel_api_key"; REVIEW="review"; COMPLETE="complete"
class TenantStatus(StrEnum): PROVISIONING="provisioning"; ACTIVE="active"; SUSPENDED="suspended"; FAILED="failed"
class RepresentativeRegistration(Base):
 __tablename__="representative_registrations"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tracking_code:Mapped[str]=mapped_column(String(32),unique=True,index=True); owner_id:Mapped[int]=mapped_column(BigInteger,index=True); brand:Mapped[str|None]=mapped_column(String(120),nullable=True); bot_id:Mapped[int|None]=mapped_column(BigInteger,nullable=True); bot_token_encrypted:Mapped[str|None]=mapped_column(Text,nullable=True); panel_url:Mapped[str|None]=mapped_column(Text,nullable=True); panel_username:Mapped[str|None]=mapped_column(String(190),nullable=True); panel_api_key_encrypted:Mapped[str|None]=mapped_column(Text,nullable=True); tenant_id:Mapped[str|None]=mapped_column(String(64),nullable=True,index=True); step:Mapped[str]=mapped_column(String(24),default=RegistrationStep.BRAND.value); status:Mapped[str]=mapped_column(String(24),default=RegistrationStatus.DRAFT.value,index=True); rejection_reason:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class TenantRecord(Base):
 __tablename__="representative_tenants"; id:Mapped[str]=mapped_column(String(64),primary_key=True); registration_id:Mapped[int]=mapped_column(Integer,unique=True,index=True); owner_id:Mapped[int]=mapped_column(BigInteger,index=True); brand:Mapped[str]=mapped_column(String(120)); bot_id:Mapped[int]=mapped_column(BigInteger,unique=True,index=True); bot_username:Mapped[str|None]=mapped_column(String(190),nullable=True); bot_token_encrypted:Mapped[str]=mapped_column(Text); panel_url:Mapped[str]=mapped_column(Text); panel_username:Mapped[str|None]=mapped_column(String(190),nullable=True); panel_api_key_encrypted:Mapped[str]=mapped_column(Text); status:Mapped[str]=mapped_column(String(24),default=TenantStatus.PROVISIONING.value,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class Plan(Base):
 __tablename__="representative_plans"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); name:Mapped[str]=mapped_column(String(120)); volume_gb:Mapped[float]=mapped_column(Float); days:Mapped[int]=mapped_column(Integer); price:Mapped[float]=mapped_column(Float); enabled:Mapped[bool]=mapped_column(Boolean,default=True,index=True); provider_template_id:Mapped[int|None]=mapped_column(Integer,nullable=True,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class RepresentativeUser(Base):
 __tablename__="representative_users"; __table_args__=(UniqueConstraint("tenant_id","telegram_user_id",name="uq_rep_user_tenant_telegram"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); telegram_user_id:Mapped[int]=mapped_column(BigInteger,index=True); username:Mapped[str|None]=mapped_column(String(190),nullable=True,index=True); first_name:Mapped[str|None]=mapped_column(String(120),nullable=True); last_name:Mapped[str|None]=mapped_column(String(120),nullable=True); balance:Mapped[float]=mapped_column(Float,default=0); blocked:Mapped[bool]=mapped_column(Boolean,default=False,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class UserBalanceLog(Base):
 __tablename__="representative_user_balance_logs"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); user_id:Mapped[int]=mapped_column(Integer,index=True); actor_id:Mapped[int]=mapped_column(BigInteger); amount:Mapped[float]=mapped_column(Float); reason:Mapped[str]=mapped_column(String(500)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Order(Base):
 __tablename__="representative_orders"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); telegram_user_id:Mapped[int]=mapped_column(BigInteger,index=True); plan_id:Mapped[int]=mapped_column(Integer,index=True); plan_name:Mapped[str]=mapped_column(String(120)); volume_gb:Mapped[float]=mapped_column(Float); days:Mapped[int]=mapped_column(Integer); amount:Mapped[float]=mapped_column(Float); status:Mapped[str]=mapped_column(String(24),default="pending",index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class CheckoutRecord(Base):
 __tablename__="representative_checkout_records"; __table_args__=(UniqueConstraint("tenant_id","order_id",name="uq_checkout_tenant_order"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); order_id:Mapped[int]=mapped_column(Integer,index=True); telegram_user_id:Mapped[int]=mapped_column(BigInteger,index=True); subtotal:Mapped[float]=mapped_column(Float); discount_amount:Mapped[float]=mapped_column(Float,default=0); total:Mapped[float]=mapped_column(Float); discount_code:Mapped[str|None]=mapped_column(String(64),nullable=True); payment_reference:Mapped[str|None]=mapped_column(String(190),nullable=True); payment_submitted_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class DiscountRedemption(Base):
 __tablename__="representative_discount_redemptions"; __table_args__=(UniqueConstraint("tenant_id","order_id",name="uq_discount_redemption_order"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); discount_id:Mapped[int]=mapped_column(Integer,index=True); order_id:Mapped[int]=mapped_column(Integer,index=True); telegram_user_id:Mapped[int]=mapped_column(BigInteger,index=True); amount:Mapped[float]=mapped_column(Float); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Discount(Base):
 __tablename__="representative_discounts"; __table_args__=(UniqueConstraint("tenant_id","code",name="uq_discount_tenant_code"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); code:Mapped[str]=mapped_column(String(64),index=True); percent:Mapped[float]=mapped_column(Float); max_uses:Mapped[int|None]=mapped_column(Integer,nullable=True); used_count:Mapped[int]=mapped_column(Integer,default=0); enabled:Mapped[bool]=mapped_column(Boolean,default=True,index=True); expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class ServiceSubscription(Base):
 __tablename__="representative_service_subscriptions"; __table_args__=(UniqueConstraint("tenant_id","order_id",name="uq_subscription_tenant_order"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); order_id:Mapped[int]=mapped_column(Integer,index=True); telegram_user_id:Mapped[int]=mapped_column(BigInteger,index=True); plan_id:Mapped[int]=mapped_column(Integer,index=True); plan_name:Mapped[str]=mapped_column(String(120)); volume_gb:Mapped[float]=mapped_column(Float); days:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(32),default="pending_provisioning",index=True); provider:Mapped[str]=mapped_column(String(40),default="pasarguard"); provider_service_id:Mapped[str|None]=mapped_column(String(190),nullable=True); subscription_url:Mapped[str|None]=mapped_column(Text,nullable=True); starts_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now()); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class TrialClaim(Base):
 __tablename__="representative_trial_claims"; __table_args__=(UniqueConstraint("tenant_id","telegram_user_id",name="uq_trial_tenant_user"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); telegram_user_id:Mapped[int]=mapped_column(BigInteger,index=True); plan_id:Mapped[int]=mapped_column(Integer); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class Referral(Base):
 __tablename__="representative_referrals"; __table_args__=(UniqueConstraint("tenant_id","referred_user_id",name="uq_referral_tenant_referred"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); inviter_user_id:Mapped[int]=mapped_column(Integer,index=True); referred_user_id:Mapped[int]=mapped_column(Integer,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class SalesSetting(Base):
 __tablename__="representative_sales_settings"; __table_args__=(UniqueConstraint("tenant_id","key",name="uq_sales_setting_tenant_key"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); key:Mapped[str]=mapped_column(String(64)); value:Mapped[str]=mapped_column(String(500)); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class RepresentativeText(Base):
 __tablename__="representative_texts"; __table_args__=(UniqueConstraint("tenant_id","key",name="uq_rep_text_tenant_key"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); key:Mapped[str]=mapped_column(String(100)); value:Mapped[str]=mapped_column(Text); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
class RepresentativeLog(Base):
 __tablename__="representative_logs"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); actor_id:Mapped[int|None]=mapped_column(BigInteger,nullable=True,index=True); action:Mapped[str]=mapped_column(String(120),index=True); details:Mapped[str]=mapped_column(String(1000),default=""); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),index=True)
class RepresentativeLink(Base):
 __tablename__="representative_links"; id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); title:Mapped[str]=mapped_column(String(120)); url:Mapped[str]=mapped_column(String(1000)); kind:Mapped[str]=mapped_column(String(40),default="general"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now())
class RepresentativeSetting(Base):
 __tablename__="representative_settings"; __table_args__=(UniqueConstraint("tenant_id","key",name="uq_rep_setting_tenant_key"),); id:Mapped[int]=mapped_column(Integer,primary_key=True,autoincrement=True); tenant_id:Mapped[str]=mapped_column(String(64),index=True); key:Mapped[str]=mapped_column(String(80)); value:Mapped[str]=mapped_column(String(1000)); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),server_default=func.now(),onupdate=func.now())
