from __future__ import annotations
from dataclasses import dataclass
from enum import StrEnum
class Area(StrEnum): CENTRAL="central"; ADMIN="representative_admin"; USER="representative_user"
@dataclass(frozen=True,slots=True)
class PageSpec:
 id:str; area:Area; title:str; purpose:str; entry:tuple[str,...]; buttons:tuple[str,...]; states:tuple[str,...]; permission:str; data_scope:str; dependencies:tuple[str,...]
PAGES=(
PageSpec("C-01",Area.CENTRAL,"Central Home","Private entry point for representative registration and tracking",("/start","central:home"),("register_representative","track_registration","track_latest","cancel"),("idle","creating_request","request_created","tracking_input","loading","empty","error"),"private owner","central database",("SQLAlchemy","Telethon")),
PageSpec("C-02",Area.CENTRAL,"Representative Registration Wizard","Collect and validate bot and Pasarguard credentials",("central:registration:continue","C-01 register"),("continue","previous","confirm","cancel"),("brand","bot_token","bot_id","panel_url","panel_username","panel_api_key","review","pending","error"),"private owner","central database",("Telegram Bot API","Pasarguard API","Fernet")),
PageSpec("C-03",Area.CENTRAL,"Central Admin Review","Review and approve/reject representative requests",("/admin","central:admin:pending"),("pending","view","approve","reject","retry","back"),("loading","ready","empty","detail","provisioning","active","failed","rejected","error"),"central admins","central database",("SQLAlchemy","ProvisioningService")),
PageSpec("C-04",Area.CENTRAL,"Tenant Provisioning","Create tenant identity and start dedicated runtime",("C-03 approve","C-03 retry"),("provision","retry","back"),("provisioning","runtime_starting","runtime_ready","active","failed"),"central lifecycle","tenant registry",("SQLAlchemy","Telethon","TenantService")),
PageSpec("A-01",Area.ADMIN,"Representative Dashboard","Owner gateway to tenant administration",("/start","/admin","rep:rep.home"),("plans","users","orders","services","discounts","sales","panel","texts","logs","links","settings"),("loading","ready","error"),"active representative owner","current tenant",("RepresentativeDashboardService",)),
PageSpec("A-02",Area.ADMIN,"Plan Management","Create and manage tenant sales plans with optional Pasarguard templates",("A-01 plans","rep:plans"),("list","add","cancel","view","toggle","delete","confirm_delete","back"),("empty","listing","creating_name","creating_volume","creating_days","creating_price","creating_template","created","error"),"active representative owner","current tenant plans",("PlanService","Pasarguard user templates","SQLAlchemy")),
PageSpec("A-03",Area.ADMIN,"User Management","Search, inspect, block users and adjust wallet",("A-01 users","rep:users"),("list","search","view","block","unblock","add_balance","subtract_balance","cancel","back"),("empty","listing","searching","detail","blocked","active","balance_input","balance_updated","error"),"active representative owner","current tenant users",("RepresentativeUserService","UserBalanceLog")),
PageSpec("A-04",Area.ADMIN,"Sales and Orders","Review payments and deliver Pasarguard services",("A-01 orders","rep:orders"),("list","view","confirm_payment","provision","retry_provision","fulfill","cancel","back"),("empty","listing","detail","pending","paid","provisioning","active","fulfilled","cancelled","error"),"active representative owner","current tenant orders and subscriptions",("OrderService","PasarguardProvisioningService","PasarguardClient","LogService")),
PageSpec("A-05",Area.ADMIN,"Discount Management","Manage discount codes and lifecycle",("A-01 discounts","rep:discounts"),("list","add","view","toggle","delete","confirm_delete","cancel","back"),("empty","listing","creating_code","creating_percent","creating_max_uses","creating_expiry","detail","active","disabled","created","error"),"active representative owner","current tenant discounts",("DiscountService","SQLAlchemy")),
PageSpec("A-06",Area.ADMIN,"Sales Settings","Persistently control sales, payment confirmation, pending orders, currency and support",("A-01 sales","rep:rep.sales"),("sales_enabled","payment_confirmation","pending_orders","currency","support","cancel","back"),("loading","ready","editing_currency","editing_support","saved","error"),"active representative owner","current tenant sales settings",("SalesSettingsService","SQLAlchemy")),
PageSpec("A-07",Area.ADMIN,"Texts and Buttons","Customize customer-facing texts and menu labels with reset support",("A-01 texts","rep:rep.texts"),("list","view","edit","reset","cancel","back"),("listing","detail","editing","saved","reset","error"),"active representative owner","current tenant text overrides",("TextService","SQLAlchemy","customer runtime")),
PageSpec("A-08",Area.ADMIN,"Audit Logs","View recent tenant-scoped administrative and sales events",("A-01 logs","rep:rep.logs"),("list","refresh","back"),("loading","empty","listing","error"),"active representative owner","current tenant audit events",("LogService","SQLAlchemy")),
PageSpec("A-09",Area.ADMIN,"Ready Links","Create, list and delete tenant-scoped ready links",("A-01 links","rep:rep.links"),("list","add","delete","cancel","back"),("empty","listing","entering_title","entering_url","saved","error"),"active representative owner","current tenant links",("LinkService","SQLAlchemy")),
PageSpec("A-10",Area.ADMIN,"Representative Settings","Manage tenant identity, support contact and timezone",("A-01 settings","rep:rep.settings"),("brand","support","timezone","cancel","back"),("loading","ready","editing","saved","error"),"active representative owner","current tenant settings",("RepresentativeSettingsService","SQLAlchemy")),
PageSpec("A-11",Area.ADMIN,"Pasarguard Panel Connection","Inspect and test the current tenant's Pasarguard panel connection without exposing secrets",("A-01 panel","rep:rep.panel"),("check","list","back"),("checking","connected","unreachable","unauthorized","missing","unknown","error"),"active representative owner","current tenant panel credentials and status",("PanelStatusService","PasarguardClient","Fernet","SQLAlchemy")),
PageSpec("A-12",Area.ADMIN,"Service Lifecycle Management","Inspect and manage tenant service delivery lifecycle",("A-01 services","rep:rep.services"),("list","filter","view","retry_provision","expire","revoke","refresh","back"),("empty","listing","pending_provisioning","provisioning","active","expired","revoked","error"),"active representative owner","current tenant subscriptions",("SubscriptionService","PasarguardProvisioningService","PasarguardClient","LogService")),
PageSpec("U-01",Area.USER,"Representative User Home","Customer entry point for browsing and purchasing services",("/start",),("buy","my_services","wallet","profile","referral","trial","support"),("loading","ready","empty","error"),"customer","current tenant",("TextService","PlanService")),
PageSpec("U-02",Area.USER,"My Services","Customer's actual Pasarguard subscriptions and delivery status",("U-01 services",),("list","view","refresh","open_subscription","back"),("loading","empty","pending_provisioning","provisioning","active","expired","revoked","error"),"customer","current tenant and user subscriptions",("UserServicesService","ServiceSubscription","PasarguardProvisioningService")),
PageSpec("U-03",Area.USER,"Wallet","Customer balance and wallet history",("U-01 wallet",),("history","refresh","back"),("loading","empty","ready","error"),"customer","current tenant and user",("UserBalanceLog",)),
PageSpec("U-04",Area.USER,"Profile","Customer identity and profile management",("U-01 profile",),("edit_name","refresh","back","cancel"),("ready","editing","saved","error"),"customer","current tenant and user",("UserProfileService",)),
PageSpec("U-05",Area.USER,"Discounts","Customer discount discovery and checkout application",("U-01 discount","U-09 checkout"),("list","apply","remove","back"),("empty","ready","applied","invalid","expired","error"),"customer","current tenant; discount redemption tied to order",("DiscountService","OrderService")),
PageSpec("U-06",Area.USER,"Trial","One-time trial claim per tenant/user",("U-01 trial",),("claim","back"),("ready","claimed","already_claimed","empty","error"),"customer","current tenant and user",("TrialService","PlanService")),
PageSpec("U-07",Area.USER,"Referrals","Referral identity, deep-link attribution and statistics",("U-01 referral","/start ref_<id>"),("share_link","refresh","back"),("ready","attached","empty","error"),"customer","current tenant and user",("ReferralService","Telegram deep links")),
PageSpec("U-08",Area.USER,"Support","Representative support contact",("U-01 support",),("contact","services","back"),("ready","unconfigured","error"),"customer","current tenant settings",("RepresentativeSettingsService",)),
PageSpec("U-09",Area.USER,"Checkout and Payment Submission","Review plan, apply discount, create order and submit payment",("U-01 buy","U-05 apply"),("review","discount","remove_discount","pay","submit_reference","cancel","back"),("review","discount_input","pending_payment","payment_submitted","paid","awaiting_confirmation","error"),"customer","current tenant; order and checkout records scoped to user",("OrderService","DiscountService","SalesSettingsService","SQLAlchemy")),
)
def get_page(page_id:str)->PageSpec:
 for page in PAGES:
  if page.id==page_id:return page
 raise KeyError(f"Unknown page: {page_id}")
